CREATE TABLE [costmg].[cost_{nombre_cliente}](
	[Id  de la cuenta (AccountId)] [int] NULL,
	[Nombre de cuenta (AccountName)] [varchar](100) NULL,
	[Correo electrónico del propietario de la cuenta (AccountOwnerEmail)] [varchar](50) NULL,
	[Información adicional (AdditionalInfo)] [varchar](1000) NULL,
	[Cantidad consumida (ConsumedQuantity)] [real] NULL,
	[Servicio consumido (ConsumedService)] [varchar](100) NULL,
	[Id  del servicio consumido (ConsumedServiceId)] [int] NULL,
	[Costo (Cost)] [real] NULL,
	[Centro de coste (CostCenter)] [varchar](255) NULL,
	[Fecha (Date)] [datetime] NULL,
	[Id  de departamento (DepartmentId)] [int] NULL,
	[Nombre de departamento (DepartmentName)] [varchar](100) NULL,
	[Id  de instancia (InstanceId)] [varchar](1000) NULL,
	[Categoría del medidor (MeterCategory)] [varchar](100) NULL,
	[Id  de medidor (MeterId)] [varchar](100) NULL,
	[Nombre del medidor (MeterName)] [varchar](2000) NULL,
	[Región del medidor (MeterRegion)] [varchar](50) NULL,
	[Subcategoría del medidor (MeterSubCategory)] [varchar](200) NULL,
	[Producto (Product)] [varchar](500) NULL,
	[Id  de producto (ProductId)] [bigint] NULL,
	[Grupo de recursos (ResourceGroup)] [varchar](500) NULL,
	[Ubicación de los recursos (ResourceLocation)] [varchar](50) NULL,
	[Id  de ubicación de recursos (ResourceLocationId)] [int] NULL,
	[Tasa de recursos (ResourceRate)] [real] NULL,
	[Id  de administrador de servicio (ServiceAdministratorId)] [varchar](255) NULL,
	[Información del servicio 1 (ServiceInfo1)] [varchar](500) NULL,
	[Información del servicio 2 (ServiceInfo2)] [varchar](500) NULL,
	[Identificador del servicio del almacén (StoreServiceIdentifier)] [varchar](255) NULL,
	[Ubicación de los recursos (SubscriptionGuid)] [varchar](40) NULL,
	[Id  de suscripción (SubscriptionId)] [bigint] NULL,
	[Nombre de la suscripción (SubscriptionName)] [varchar](200) NULL,
	[Etiquetas (Tags)] [varchar](3000) NULL,
	[Unidad de medida (UnitOfMeasure)] [varchar](50) NULL,
	[PartNumber (PartNumber)] [varchar](50) NULL,
	[ResourceGuid ] [varchar](190) NULL,
	[OfferId (OfferId)] [varchar](190) NULL,
	[ChargesBilledSeparately (ChargesBilledSeparately)] [varchar](190) NULL,
	[ServiceName (ServiceName)] [varchar](100) NULL,
	[ServiceTier (ServiceTier)] [varchar](100) NULL,
	[ChargeType] [nvarchar](200) NULL,
	[UnitPrice] [real] NULL,
	[ReservationId] [nvarchar](200) NULL,
	[ReservationName] [nvarchar](200) NULL,
	[ResourceName] [nvarchar](200) NULL
)


CREATE TABLE [dbo].[cost_stg_{nombre_cliente}](
	[InvoiceSectionName] [nvarchar](100) NULL,
	[AccountName] [nvarchar](500) NULL,
	[AccountOwnerId] [nvarchar](500) NULL,
	[SubscriptionId] [nvarchar](500) NULL,
	[SubscriptionName] [nvarchar](500) NULL,
	[ResourceGroup] [nvarchar](500) NULL,
	[ResourceLocation] [nvarchar](500) NULL,
	[Date] [date] NULL,
	[ProductName] [nvarchar](100) NULL,
	[MeterCategory] [nvarchar](200) NULL,
	[MeterSubCategory] [nvarchar](200) NULL,
	[MeterId] [nvarchar](500) NULL,
	[MeterName] [nvarchar](500) NULL,
	[MeterRegion] [nvarchar](500) NULL,
	[UnitOfMeasure] [nvarchar](200) NULL,
	[Quantity] [real] NULL,
	[EffectivePrice] [nvarchar](500) NULL,
	[CostInBillingCurrency] [real] NULL,
	[CostCenter] [nvarchar](500) NULL,
	[ConsumedService] [nvarchar](500) NULL,
	[ResourceId] [nvarchar](500) NULL,
	[Tags] [nvarchar](500) NULL,
	[OfferId] [nvarchar](500) NULL,
	[AdditionalInfo] [nvarchar](500) NULL,
	[ServiceInfo1] [nvarchar](500) NULL,
	[ServiceInfo2] [nvarchar](500) NULL,
	[ResourceName] [nvarchar](500) NULL,
	[ReservationId] [nvarchar](500) NULL,
	[ReservationName] [nvarchar](500) NULL,
	[UnitPrice] [real] NULL,
	[ProductOrderId] [nvarchar](500) NULL,
	[ProductOrderName] [nvarchar](500) NULL,
	[Term] [nvarchar](500) NULL,
	[PublisherType] [nvarchar](500) NULL,
	[PublisherName] [nvarchar](500) NULL,
	[ChargeType] [nvarchar](500) NULL,
	[Frequency] [nvarchar](500) NULL,
	[PricingModel] [nvarchar](500) NULL,
	[AvailabilityZone] [nvarchar](500) NULL,
	[BillingAccountId] [nvarchar](500) NULL,
	[BillingAccountName] [nvarchar](500) NULL,
	[BillingCurrencyCode] [nvarchar](500) NULL,
	[BillingPeriodStartDate] [nvarchar](500) NULL,
	[BillingPeriodEndDate] [nvarchar](500) NULL,
	[BillingProfileId] [nvarchar](500) NULL,
	[BillingProfileName] [nvarchar](500) NULL,
	[InvoiceSectionId] [nvarchar](500) NULL,
	[IsAzureCreditEligible] [nvarchar](500) NULL,
	[PartNumber] [nvarchar](50) NULL,
	[PayGPrice] [nvarchar](500) NULL,
	[PlanName] [nvarchar](500) NULL,
	[ServiceFamily] [nvarchar](500) NULL,
	[CostAllocationRuleName] [nvarchar](500) NULL,
	[benefitId] [nvarchar](500) NULL,
	[benefitName] [nvarchar](500) NULL
)